import type { Config } from "tailwindcss"

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-poppins)", "system-ui", "-apple-system", "Segoe UI", "Roboto", "Helvetica", "Arial", "sans-serif"],
        display: ["var(--font-poppins)", "system-ui", "-apple-system", "sans-serif"],
        mono: ["ui-monospace", "SF Mono", "Menlo", "Consolas", "Liberation Mono", "monospace"],
      },
      colors: {
        // DKube brand scale
        "dk-purple-900": "#4A3878",
        "dk-purple-800": "#5C4A8E",
        "dk-purple-700": "#7660A8",
        "dk-purple-600": "#8773B5",
        "dk-purple-500": "#9384BD",
        "dk-purple-400": "#B0A4CE",
        "dk-purple-300": "#C9C0DE",
        "dk-purple-200": "#E2DCEE",
        "dk-purple-100": "#F1EEF8",
        "dk-purple-50": "#F8F6FB",
        // DKube neutrals
        "dk-ink": "#0F0F12",
        "dk-gray-900": "#1A1A20",
        "dk-gray-800": "#2B2B33",
        "dk-gray-700": "#404049",
        "dk-gray-600": "#5A5A66",
        "dk-gray-500": "#7A7A85",
        "dk-gray-400": "#A3A3AC",
        "dk-gray-300": "#D6D6D6",
        "dk-gray-200": "#E8E8EC",
        "dk-gray-100": "#F2F2F4",
        "dk-gray-50": "#F8F8FA",
        "dk-white": "#FFFFFF",
        // DKube semantic
        "dk-success": "#2E8B57",
        "dk-success-bg": "#E6F4EC",
        "dk-warning": "#C28A00",
        "dk-warning-bg": "#FBF1DC",
        "dk-danger": "#B3261E",
        "dk-danger-bg": "#FBE9E7",
        "dk-info": "#2C6CB0",
        "dk-info-bg": "#E5EFF9",
        // Calendar accent
        "cal-green": "#10B981",
        // Semantic tokens (map to CSS vars)
        "dk-bg": "var(--dk-bg)",
        "dk-bg-muted": "var(--dk-bg-muted)",
        "dk-bg-tint": "var(--dk-bg-tint)",
        "dk-fg": "var(--dk-fg)",
        "dk-fg-1": "var(--dk-fg-1)",
        "dk-fg-2": "var(--dk-fg-2)",
        "dk-fg-muted": "var(--dk-fg-muted)",
        "dk-brand": "var(--dk-brand)",
        "dk-brand-hover": "var(--dk-brand-hover)",
        "dk-border": "var(--dk-border)",
        "dk-border-strong": "var(--dk-border-strong)",
        // Keep shadcn compatibility tokens
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        "dk-xs": "4px",
        "dk-sm": "8px",
        "dk-md": "12px",
        "dk-lg": "16px",
        "dk-xl": "24px",
        "dk-2xl": "32px",
        "dk-pill": "999px",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      boxShadow: {
        "dk-xs": "0 1px 2px rgba(15,15,18,0.04)",
        "dk-sm": "0 2px 6px rgba(15,15,18,0.06)",
        "dk-md": "0 8px 20px rgba(15,15,18,0.08)",
        "dk-lg": "0 18px 40px rgba(15,15,18,0.10)",
        "dk-brand": "0 12px 28px rgba(118,96,168,0.28)",
      },
      spacing: {
        "dk-1": "4px",
        "dk-2": "8px",
        "dk-3": "12px",
        "dk-4": "16px",
        "dk-5": "20px",
        "dk-6": "24px",
        "dk-8": "32px",
        "dk-10": "40px",
        "dk-12": "48px",
        "dk-16": "64px",
        "dk-20": "80px",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
export default config
